/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#8a4cfc",
        "tertiary-container": "#885500",
        "on-background": "#191c1e",
        "on-primary-fixed-variant": "#3323cc",
        "background": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-primary": "#ffffff",
        "secondary-fixed": "#eaddff",
        "on-primary-container": "#dad7ff",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#d2bbff",
        "primary-fixed": "#e2dfff",
        "outline-variant": "#c7c4d8",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface-variant": "#464555",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed": "#0f0069",
        "secondary": "#712ae2",
        "primary-container": "#4f46e5",
        "primary": "#3525cd",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-tint": "#4d44e3",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#5a00c6",
        "inverse-primary": "#c3c0ff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-fixed": "#25005a",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "outline": "#777587",
        "on-tertiary-container": "#ffd4a4",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error": "#ffffff",
        "tertiary": "#684000",
        "on-tertiary-fixed": "#2a1700"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-sm": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
